GET http://localhost:5000/text2img
    ?prompt=beautiful slavic young woman in traditional russian outfit under sunbeams in a field with flowers, high quality, highly detailed, real photo, 8k
    &num_steps=50
    &guidance_scale=1
